info:
  contact:
    email: xxxx@126.com
    name: demo
  description: demo项目
  title: 接囗文档
  version: "1.0"
paths:
  /hello:
    get:
      responses: {}
  /redis/getRedis:
    get:
      parameters:
      - description: Key
        in: query
        name: key
        required: true
        type: string
      responses: {}
  /redis/setRedis:
    get:
      parameters:
      - description: key
        in: query
        name: key
        required: true
        type: string
      - description: value
        in: query
        name: value
        required: true
        type: string
      responses: {}
  /user/getUser:
    get:
      responses: {}
  /user/getUserAndRole:
    get:
      responses: {}
swagger: "2.0"
